### ISSUE TITLE
[Question] Nuget or Implement

### ISSUE THREAD

**Issue by generik0** [fir3pho3nixx/Windsor.AspNetCore#1]
Hi fir3pho3nixx
I am starting a new aspnetcore project. Thought i might get castle into aspnetcore. I found your solution here.
Should i wait for the nuget, og implement in my code?

Regards, G

**Comment by fir3pho3nixx** [comment]
Hi, thanks for looking. The PR is open here: https://github.com/castleproject/Windsor/pull/376

Once this is merged we intend to release it to nuget with id "Castle.Facilities.AspNetCore". If you compile to suit your needs for now and then when the NuGet arrives you should literally be able to swap it out. We will try to not rename and public api's where possible.

**Comment by generik0** [comment]
Cool. Great work by the way...
Keep on Keepin on ;-)

**Comment by generik0** [comment]
BTW i really like that i can configure the container in Configure.
Autofac you have to do it in ConfigureServices
