### ISSUE TITLE
No nuget package Castle.Facilities.AspNetCore available

### ISSUE THREAD

**Issue by gavinbarron** [fir3pho3nixx/Windsor.AspNetCore#3]
The nuget package mentioned in the ReadMe is not available.

I currently am using a private build of this but would really prefer to be using a published package. Is there an eta? I read the other issue #1 and the linked PR is shown as Merged.

Raising this so that I have an item to track for the publishing of the documented package

BTW, thanks for this it's really useful!

**Comment by fir3pho3nixx** [comment]
Hi,

Thanks for the interest. Please update your copy with the one that lives in the master repo of the Windsor project here: https://github.com/castleproject/Windsor/tree/master/src/Castle.Facilities.AspNetCore.

We intend to release it fairly soon. I am busy finishing off getting rid of some of the obsolescence/old facilities at which point we will publish to NuGet. 

Watch the Windsor repo for a V5 release. 

Enjoy :)
