### ISSUE TITLE
ComponentNotFoundException when running in Release mode

### ISSUE THREAD

**Issue by frankieleef** [fir3pho3nixx/Windsor.AspNetCore#6]
When running my dotnet core application in release mode using the AspNetCore Facility I run into a ComponentNotFoundException where it can't find my Controllers. When running it in Debug mode, everything seems to work as expected.

**How to reproduce**
Create a dotnet core Web API and install the AspNetCore facility.
Run the app in Debug mode. Everything should be working as expected.
Run the app in Release mode. ComponentNotFoundException is thrown.

**Versions tested**
0.0.374
aspnet-core-windsor-final

`ComponentNotFoundException: No component for supporting the service Namespace.Controllers.ValuesController was found
Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, IDictionary arguments, IReleasePolicy policy)
Castle.Facilities.AspNetCore.AspNetCoreMvcExtensions+<>c__DisplayClass0_0.<AddCustomControllerActivation>b__0(ControllerContext context)
Castle.Facilities.AspNetCore.Activators.DelegatingControllerActivator.Create(ControllerContext context)
Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()`

My `Startup.cs` looks the following:

```
public class Startup
    {
        private readonly WindsorContainer container = new WindsorContainer();
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddCastleWindsor(container);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            RegisterApplicationComponents();

            app.UseMvc();
        }

        private void RegisterApplicationComponents()
        {
            container.Install(new ContainerInstaller(Configuration));
        }
    }
```

`ContainerInstaller.cs`

```
 public class ContainerInstaller : IWindsorInstaller
    {
        private Microsoft.Extensions.Configuration.IConfiguration _configuration;

        public ContainerInstaller(Microsoft.Extensions.Configuration.IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.Register(Component.For<IBaseRepository>().ImplementedBy<MongoDBRepository>().LifestyleTransient());
            container.Register(Component.For<IConfiguration>().ImplementedBy<MongoConfiguration>().LifestyleTransient());

            container.Register(Component.For<NamespaceService>().LifestyleTransient());

            container.Register(Component.For<Namespace.PersonResolver>().LifestyleTransient());
            container.Register(Component.For<Namespace.ChildResolver>().LifestyleTransient());
            container.Register(Component.For<Namespace.HouseResolver>().LifestyleTransient());
            container.Register(Component.For<Namespace.IncomeResolver>().LifestyleTransient());

            container.Register(Component.For<NamespaceResponseConverter>().LifestyleTransient());
            container.Register(Component.For<Namespace.CalculationConverter>().LifestyleTransient());

            container.Register(
                Component.For<IMapper>().UsingFactoryMethod(x =>
                {
                    return new MapperConfiguration(c =>
                    {
                        c.ConstructServicesUsing(container.Resolve);
                        c.AddProfile<Namespace.Mapper>();
                    }).CreateMapper();
                }));
```
**Update**

I have been running my app on IISExpress. I cloned this repository and when running the WebApp in release mode I am not facing any problems.

**Comment by frankieleef** [comment]
I found a fix for the problem above. Apparently I need to add the container registrations to the `ConfigureServices` method. I moved the call to `RegisterApplicationComponents()` in to the `ConfigureServices` and after that the application runs without any problems in release mode. Silly mistake

**Comment by frankieleef** [comment]
That fixed it! It does feel weird to me that this issue does not occur when running in debug mode. I would say that besides some different configuration, it is still running the same binaries from the same location?

**Comment by fir3pho3nixx** [comment]
It is a strange problem, the only difference I can see is that it uses `netcoreapp2.0\Release` folder. I did anticipate things like this would happen under different hosting conditions like IIS but not for a vanilla web host running in a console app. I will be sure to update documentation to mention this. 

I have just pushed a massive performance improvement on the https://github.com/fir3pho3nixx/Windsor/tree/aspnet-core-windsor-final branch. The operating memory footprint should level off at 150MB and you should see throughput in the excess of 250+ requests/second.

**Comment by frankieleef** [comment]
I would like to help you trying to debug this issue and figure out why this is happening. However, I'm not able to get this running on my local machine (I used the nuget packages before). Whenever I reference Castle.Windsor from Castle.Facilities.AspNetCore I get the error that Castle.Windsor is not compatible with .netstandard2.0. Is there a specific way of setting this up?

That's great news. I am currently migrating existing .NET 4.5 applications to .NET Core. When I have these up and running I will run some extra tests using this facility

**Comment by fir3pho3nixx** [comment]
Ok, I think I have fixed the problem. Looks like GetCallingAssembly is not doing the right thing when running in Release mode. I opted for defining an entry assembly in a options object which can be overridden or has the following precedence

```csharp
internal Assembly EntryAssembly
{
	get
	{
		try
		{
			entryAssembly = entryAssembly ?? Assembly.GetEntryAssembly();
		}
		catch
		{
			entryAssembly = entryAssembly ?? Assembly.GetCallingAssembly();
		}

		return entryAssembly;
	}
}
```

See here for the full source: https://github.com/fir3pho3nixx/Windsor/blob/5d48e2c78b4d32c87ba488092899a48d2935c207/src/Castle.Facilities.AspNetCore/CastleWindsorRegistrationExtensions.cs#L36
